/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycalc;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Family
 */
public class BasicCalc extends javax.swing.JFrame {

    /**
     * Creates new form BasicCalc
     */
    int cont=0;
    float primerNumero;
    float segundoNumero;
    String operador;
    String tipoLetra="Tahoma";
    
    //Declaramos arrayList de la clase JButton para almacenar botones
    ArrayList<JButton> botones = new ArrayList<JButton>();
    
    public BasicCalc() {
        initComponents();        
        //Add an image as icon at main window.
        setIconImage(new ImageIcon(getClass().getResource("../icons/calc.png")).getImage());
        botones.add(Btn0);
        botones.add(Btn1);
        botones.add(Btn2);
        botones.add(Btn3);
        botones.add(Btn4);
        botones.add(Btn5);
        botones.add(Btn6);
        botones.add(Btn7);
        botones.add(Btn8);
        botones.add(Btn9);
        botones.add(Btn10);
        botones.add(Btn11);
        botones.add(Btn12);
        botones.add(Btn13);
        botones.add(Btn14);
        botones.add(Btn15);
        botones.add(Btn16);
        botones.add(Btn17);
        botones.add(Btn18);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblDisplay = new javax.swing.JLabel();
        Btn11 = new javax.swing.JButton();
        Btn10 = new javax.swing.JButton();
        Btn12 = new javax.swing.JButton();
        Btn13 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn14 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn15 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn16 = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        Btn18 = new javax.swing.JButton();
        Btn17 = new javax.swing.JButton();
        lblOp = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_Classic = new javax.swing.JMenuItem();
        jMenuItem_Darkula = new javax.swing.JMenuItem();
        jMenuItem_Ligth = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_TextColorBlack = new javax.swing.JMenuItem();
        jMenuItem_TextColorRed = new javax.swing.JMenuItem();
        jMenuItem_TextColorWhite = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem_TextFontArial = new javax.swing.JMenuItem();
        jMenuItem_TextFontCalibri = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_TextSize12 = new javax.swing.JMenuItem();
        jMenuItem_TextSize14 = new javax.swing.JMenuItem();
        jMenuItem_TextSize18 = new javax.swing.JMenuItem();
        jMenuItem_TextSize20 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_TextAligment = new javax.swing.JMenu();
        jMenuItem_TextAligmentCenter = new javax.swing.JMenuItem();
        jMenuItem_TextAligmentLeft = new javax.swing.JMenuItem();
        jMenuItem_TextAligmentRight = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Calc");
        setResizable(false);

        lblDisplay.setBackground(new java.awt.Color(255, 255, 255));
        lblDisplay.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisplay.setText("0");
        lblDisplay.setOpaque(true);

        Btn11.setBackground(new java.awt.Color(153, 153, 153));
        Btn11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn11.setText("+/-");
        Btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn11ActionPerformed(evt);
            }
        });

        Btn10.setBackground(new java.awt.Color(153, 153, 153));
        Btn10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn10.setText("AC");
        Btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn10ActionPerformed(evt);
            }
        });

        Btn12.setBackground(new java.awt.Color(153, 153, 153));
        Btn12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn12.setText("%");
        Btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn12ActionPerformed(evt);
            }
        });

        Btn13.setBackground(new java.awt.Color(153, 153, 153));
        Btn13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn13.setText("/");
        Btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn13ActionPerformed(evt);
            }
        });

        Btn7.setBackground(new java.awt.Color(153, 153, 153));
        Btn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn8.setBackground(new java.awt.Color(153, 153, 153));
        Btn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn9.setBackground(new java.awt.Color(153, 153, 153));
        Btn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        Btn14.setBackground(new java.awt.Color(153, 153, 153));
        Btn14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn14.setText("*");
        Btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn14ActionPerformed(evt);
            }
        });

        Btn4.setBackground(new java.awt.Color(153, 153, 153));
        Btn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setBackground(new java.awt.Color(153, 153, 153));
        Btn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn6.setBackground(new java.awt.Color(153, 153, 153));
        Btn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        Btn15.setBackground(new java.awt.Color(153, 153, 153));
        Btn15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn15.setText("-");
        Btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn15ActionPerformed(evt);
            }
        });

        Btn1.setBackground(new java.awt.Color(153, 153, 153));
        Btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setBackground(new java.awt.Color(153, 153, 153));
        Btn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setBackground(new java.awt.Color(153, 153, 153));
        Btn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn16.setBackground(new java.awt.Color(153, 153, 153));
        Btn16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn16.setText("+");
        Btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn16ActionPerformed(evt);
            }
        });

        Btn0.setBackground(new java.awt.Color(153, 153, 153));
        Btn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        Btn18.setBackground(new java.awt.Color(153, 153, 153));
        Btn18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn18.setText(".");
        Btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn18ActionPerformed(evt);
            }
        });

        Btn17.setBackground(new java.awt.Color(153, 153, 153));
        Btn17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn17.setText("=");
        Btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn17ActionPerformed(evt);
            }
        });

        lblOp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addComponent(Btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOp)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenu3.setText("Skins");

        jMenuItem_Classic.setText("Classic");
        jMenuItem_Classic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ClassicActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Classic);

        jMenuItem_Darkula.setText("Darkula");
        jMenuItem_Darkula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DarkulaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Darkula);

        jMenuItem_Ligth.setText("Light");
        jMenuItem_Ligth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LigthActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_Ligth);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jMenu6.setText("Font");

        jMenu8.setText("Text color");

        jMenuItem_TextColorBlack.setText("Black");
        jMenuItem_TextColorBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextColorBlackActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_TextColorBlack);

        jMenuItem_TextColorRed.setText("Red");
        jMenuItem_TextColorRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextColorRedActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_TextColorRed);

        jMenuItem_TextColorWhite.setText("White");
        jMenuItem_TextColorWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextColorWhiteActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_TextColorWhite);

        jMenu6.add(jMenu8);

        jMenu10.setText("Text font");

        jMenuItem_TextFontArial.setText("Arial");
        jMenuItem_TextFontArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextFontArialActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem_TextFontArial);

        jMenuItem_TextFontCalibri.setText("Calibri");
        jMenuItem_TextFontCalibri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextFontCalibriActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem_TextFontCalibri);

        jMenu6.add(jMenu10);

        jMenu7.setText("Text size");

        jMenuItem_TextSize12.setText("12");
        jMenuItem_TextSize12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextSize12ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_TextSize12);

        jMenuItem_TextSize14.setText("14");
        jMenuItem_TextSize14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextSize14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_TextSize14);

        jMenuItem_TextSize18.setText("18");
        jMenuItem_TextSize18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextSize18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_TextSize18);

        jMenuItem_TextSize20.setText("20");
        jMenuItem_TextSize20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextSize20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_TextSize20);

        jMenu6.add(jMenu7);
        jMenu6.add(jSeparator4);

        jMenuItem_TextAligment.setText("Display aligment");

        jMenuItem_TextAligmentCenter.setText("Center");
        jMenuItem_TextAligmentCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextAligmentCenterActionPerformed(evt);
            }
        });
        jMenuItem_TextAligment.add(jMenuItem_TextAligmentCenter);

        jMenuItem_TextAligmentLeft.setText("Left");
        jMenuItem_TextAligmentLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextAligmentLeftActionPerformed(evt);
            }
        });
        jMenuItem_TextAligment.add(jMenuItem_TextAligmentLeft);

        jMenuItem_TextAligmentRight.setText("Right");
        jMenuItem_TextAligmentRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_TextAligmentRightActionPerformed(evt);
            }
        });
        jMenuItem_TextAligment.add(jMenuItem_TextAligmentRight);

        jMenu6.add(jMenuItem_TextAligment);

        jMenu1.add(jMenu6);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Info");

        jMenuItem5.setText("Help");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator2);

        jMenuItem6.setText("About of ...");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Type");

        jMenuItem7.setText("Basic");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Scientific");
        jMenu4.add(jMenuItem8);

        jMenu5.setText("Others");

        jMenuItem9.setText("Vol");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Mass");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Information");
        jMenu5.add(jMenuItem11);
        jMenu5.add(jSeparator3);

        jMenuItem12.setText("Temperature");
        jMenu5.add(jMenuItem12);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        // TODO add your handling code here:
        //String displayVal = lblDisplay.getText();
        //lblDisplay.setText(displayVal + "1");
        
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("1");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "1");
        }
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        // TODO add your handling code here:

        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("2");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "2");
        }
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        // TODO add your handling code here:
        
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("3");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "3");
        }
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        // TODO add your handling code here:
   
        
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("4");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "4");
        }
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        // TODO add your handling code here:
        
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("5");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "5");
        }
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        // TODO add your handling code here:
        
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("6");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "6");
        }
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        // TODO add your handling code here:
   
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("7");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "7");
        }
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        // TODO add your handling code here:
   
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("8");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "8");
        }
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        // TODO add your handling code here:
    
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("9");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "9");
        }
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10ActionPerformed
        // TODO add your handling code here:
        lblDisplay.setText("0");
        lblOp.setText("0");
    }//GEN-LAST:event_Btn10ActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        // TODO add your handling code here:
        //lblDisplay.setText("0");
        
        if (lblDisplay.getText() == "0") {
            lblDisplay.setText("0");
        }else {
            lblDisplay.setText(lblDisplay.getText() + "0");
        }
    }//GEN-LAST:event_Btn0ActionPerformed

    private void jMenuItem_TextFontArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextFontArialActionPerformed
        tipoLetra="Arial";
        
        lblOp.setFont(new Font(tipoLetra, Font.BOLD, 18));
        
        lblDisplay.setFont(new Font(tipoLetra, Font.BOLD, 60));
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setFont(new Font(tipoLetra, Font.BOLD, 18));
        }   
        
    }//GEN-LAST:event_jMenuItem_TextFontArialActionPerformed

    private void jMenuItem_DarkulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DarkulaActionPerformed
        // TODO add your handling code here:
             
        lblOp.setForeground(Color.white);
        
        //Change Panel background color
        pnlMain.setBackground(Color.black);
        
        //Change Label display background color
        lblDisplay.setBackground(Color.black);
        
        //Change Display text color
        lblDisplay.setForeground(Color.white);
        //Darcula Style buttons
                
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setBackground(Color.orange);
            botones.get(i).setForeground(Color.white);
            botones.get(i).setFont(new Font("Tahoma", Font.BOLD, 18));
        }

    }//GEN-LAST:event_jMenuItem_DarkulaActionPerformed

    private void Btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn16ActionPerformed
        // TODO add your handling code here:
        primerNumero=Float.parseFloat(lblDisplay.getText());
        operador="+";
        lblDisplay.setText("");
        lblOp.setText(primerNumero+" "+operador);
    }//GEN-LAST:event_Btn16ActionPerformed

    private void Btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn15ActionPerformed
        // TODO add your handling code here:
        primerNumero=Float.parseFloat(lblDisplay.getText());
        operador="-";
        lblDisplay.setText("");
        lblOp.setText(primerNumero+" "+operador);
    }//GEN-LAST:event_Btn15ActionPerformed

    private void Btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn14ActionPerformed
        // TODO add your handling code here:
        primerNumero=Float.parseFloat(lblDisplay.getText());
        operador="*";
        lblDisplay.setText("");
        lblOp.setText(primerNumero+" "+operador);

    }//GEN-LAST:event_Btn14ActionPerformed

    private void Btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn13ActionPerformed
        // TODO add your handling code here:
       primerNumero=Float.parseFloat(lblDisplay.getText());
       operador="/";
       lblDisplay.setText("");
       lblOp.setText(primerNumero+" "+operador);

    }//GEN-LAST:event_Btn13ActionPerformed

    private void Btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn11ActionPerformed
        // TODO add your handling code here:
        if (lblDisplay.getText().equals("0")) {
            lblDisplay.setText("0");            
        }else{
            float numero=Float.parseFloat(lblDisplay.getText());
            if(numero>0){ 
                //Si el número es positivo hacer lo siguiente: Añadir el signo -
                lblDisplay.setText("-" + numero);
                lblOp.setText("-" + numero);

            }else if(numero<0){  
                //Si el número es negativo hacer lo siguiente: Quitar el signo -
                lblDisplay.setText(Float.toString(numero).substring(1));
                lblOp.setText(Float.toString(numero).substring(1));
            }
        }
    }//GEN-LAST:event_Btn11ActionPerformed

    private void jMenuItem_ClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ClassicActionPerformed
        // TODO add your handling code here:
        
        Color color = new Color(240,240,240);
        
        lblOp.setForeground(Color.black);
        
        //Change Panel background color
        pnlMain.setBackground(color);
        
        //Change Label display background color
        lblDisplay.setBackground(Color.white);
        
        //Change Display text color
        lblDisplay.setForeground(Color.black);
        //Darcula Style buttons
        
        Color color_btn = new Color(153,153,153);              
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setBackground(color_btn);
            botones.get(i).setForeground(Color.black);
            botones.get(i).setFont(new Font("Tahoma", Font.BOLD, 18));
        }
    }//GEN-LAST:event_jMenuItem_ClassicActionPerformed

    private void jMenuItem_LigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LigthActionPerformed
        // TODO add your handling code here:
        lblOp.setForeground(Color.black);
        
        pnlMain.setBackground(Color.white);
        
        lblDisplay.setBackground(Color.white);
        
        lblDisplay.setForeground(Color.black);
                
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setBackground(Color.orange);
            botones.get(i).setForeground(Color.black);
            botones.get(i).setFont(new Font("Tahoma", Font.BOLD, 18));
        }
    }//GEN-LAST:event_jMenuItem_LigthActionPerformed

    private void Btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn12ActionPerformed
        // TODO add your handling code here:
        primerNumero=Float.parseFloat(lblDisplay.getText());
        operador="%";
        lblDisplay.setText("");
        lblOp.setText(primerNumero+" "+operador);
       
    }//GEN-LAST:event_Btn12ActionPerformed

    private void Btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn17ActionPerformed
        // TODO add your handling code here:
        float resultado=0;
        segundoNumero=Float.parseFloat(lblDisplay.getText());
        switch(operador){
            case "+":
                resultado=primerNumero+segundoNumero;
                lblDisplay.setText(Float.toString(resultado));
                lblOp.setText(primerNumero+" "+operador+" "+segundoNumero+" "+"= "+resultado);
                break;
            case "-":
                resultado=primerNumero-segundoNumero;
                lblDisplay.setText(Float.toString(resultado));
                lblOp.setText(primerNumero+" "+operador+" "+segundoNumero+" "+"= "+resultado);
                break;
            case "*":
                resultado=primerNumero*segundoNumero;                
                lblDisplay.setText(Float.toString(resultado));
                lblOp.setText(primerNumero+" "+operador+" "+segundoNumero+" "+"= "+resultado);   
                break;
            case "/":
                resultado=primerNumero/segundoNumero;                
                lblDisplay.setText(Float.toString(resultado));
                lblOp.setText(primerNumero+" "+operador+" "+segundoNumero+" "+"= "+resultado);
                break;
            case "%":
                resultado=primerNumero%segundoNumero;                
                lblDisplay.setText(Float.toString(resultado));
                lblOp.setText(primerNumero+" "+operador+" "+segundoNumero+" "+"= "+resultado);
                break;
        }
    }//GEN-LAST:event_Btn17ActionPerformed

    private void Btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn18ActionPerformed
        // TODO add your handling code here:
        lblDisplay.setText(lblDisplay.getText()+".");
        lblOp.setText(lblDisplay.getText());
    }//GEN-LAST:event_Btn18ActionPerformed

    private void jMenuItem_TextColorBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextColorBlackActionPerformed
        // TODO add your handling code here:
                
        lblOp.setForeground(Color.black);
        
        lblDisplay.setForeground(Color.black);
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setForeground(Color.black);
        }
    }//GEN-LAST:event_jMenuItem_TextColorBlackActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem_TextColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextColorRedActionPerformed
        // TODO add your handling code here:
        lblOp.setForeground(Color.red);
        
        lblDisplay.setForeground(Color.red);
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setForeground(Color.red);
        }
    }//GEN-LAST:event_jMenuItem_TextColorRedActionPerformed

    private void jMenuItem_TextColorWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextColorWhiteActionPerformed
        // TODO add your handling code here:
        lblOp.setForeground(Color.white);
        
        lblDisplay.setForeground(Color.white);
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setForeground(Color.white);
        }
    }//GEN-LAST:event_jMenuItem_TextColorWhiteActionPerformed

    private void jMenuItem_TextFontCalibriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextFontCalibriActionPerformed
        // TODO add your handling code here:        
        tipoLetra="Calibri";

        lblOp.setFont(new Font(tipoLetra, Font.BOLD, 18));
        
        lblDisplay.setFont(new Font(tipoLetra, Font.BOLD, 60));
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setFont(new Font(tipoLetra, Font.BOLD, 18));
        }   
    }//GEN-LAST:event_jMenuItem_TextFontCalibriActionPerformed

    private void jMenuItem_TextSize12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextSize12ActionPerformed
        // TODO add your handling code here:
        lblOp.setFont(new Font(tipoLetra, Font.BOLD, 12));
        
        lblDisplay.setFont(new Font(tipoLetra, Font.BOLD, 12));
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setFont(new Font(tipoLetra, Font.BOLD, 12));
        }
    }//GEN-LAST:event_jMenuItem_TextSize12ActionPerformed

    private void jMenuItem_TextSize14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextSize14ActionPerformed
        // TODO add your handling code here:
        lblOp.setFont(new Font(tipoLetra, Font.BOLD, 14));
        
        lblDisplay.setFont(new Font(tipoLetra, Font.BOLD, 14));
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setFont(new Font(tipoLetra, Font.BOLD, 14));
        }
    }//GEN-LAST:event_jMenuItem_TextSize14ActionPerformed

    private void jMenuItem_TextSize18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextSize18ActionPerformed
        // TODO add your handling code here:
        lblOp.setFont(new Font(tipoLetra, Font.BOLD, 18));
        
        lblDisplay.setFont(new Font(tipoLetra, Font.BOLD, 18));
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setFont(new Font(tipoLetra, Font.BOLD, 18));
        }
    }//GEN-LAST:event_jMenuItem_TextSize18ActionPerformed

    private void jMenuItem_TextSize20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextSize20ActionPerformed
        // TODO add your handling code here:
        lblOp.setFont(new Font(tipoLetra, Font.BOLD, 20));
        
        lblDisplay.setFont(new Font(tipoLetra, Font.BOLD, 20));
        
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setFont(new Font(tipoLetra, Font.BOLD, 20));
        }
    }//GEN-LAST:event_jMenuItem_TextSize20ActionPerformed

    private void jMenuItem_TextAligmentCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextAligmentCenterActionPerformed
        // TODO add your handling code here:
        lblDisplay.setHorizontalAlignment(lblDisplay.CENTER);
    }//GEN-LAST:event_jMenuItem_TextAligmentCenterActionPerformed

    private void jMenuItem_TextAligmentLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextAligmentLeftActionPerformed
        // TODO add your handling code here:
        lblDisplay.setHorizontalAlignment(lblDisplay.LEFT);
    }//GEN-LAST:event_jMenuItem_TextAligmentLeftActionPerformed

    private void jMenuItem_TextAligmentRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_TextAligmentRightActionPerformed
        // TODO add your handling code here:
        lblDisplay.setHorizontalAlignment(lblDisplay.RIGHT);
    }//GEN-LAST:event_jMenuItem_TextAligmentRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn10;
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn12;
    private javax.swing.JButton Btn13;
    private javax.swing.JButton Btn14;
    private javax.swing.JButton Btn15;
    private javax.swing.JButton Btn16;
    private javax.swing.JButton Btn17;
    private javax.swing.JButton Btn18;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_Classic;
    private javax.swing.JMenuItem jMenuItem_Darkula;
    private javax.swing.JMenuItem jMenuItem_Ligth;
    private javax.swing.JMenu jMenuItem_TextAligment;
    private javax.swing.JMenuItem jMenuItem_TextAligmentCenter;
    private javax.swing.JMenuItem jMenuItem_TextAligmentLeft;
    private javax.swing.JMenuItem jMenuItem_TextAligmentRight;
    private javax.swing.JMenuItem jMenuItem_TextColorBlack;
    private javax.swing.JMenuItem jMenuItem_TextColorRed;
    private javax.swing.JMenuItem jMenuItem_TextColorWhite;
    private javax.swing.JMenuItem jMenuItem_TextFontArial;
    private javax.swing.JMenuItem jMenuItem_TextFontCalibri;
    private javax.swing.JMenuItem jMenuItem_TextSize12;
    private javax.swing.JMenuItem jMenuItem_TextSize14;
    private javax.swing.JMenuItem jMenuItem_TextSize18;
    private javax.swing.JMenuItem jMenuItem_TextSize20;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblOp;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
