package ejercicios;

import java.awt.Color;
import javax.swing.border.TitledBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JUAN CARLOS ASTAIZA
 */
public class StringManager extends javax.swing.JFrame {
        String yName="";
    /**
     * Creates new form StringManager
     */
    public StringManager() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnSpanish = new javax.swing.JButton();
        btnEnglish = new javax.swing.JButton();
        jPInformation = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        lolName = new javax.swing.JLabel();
        jLabelNameMay = new javax.swing.JLabel();
        jLabelNameMin = new javax.swing.JLabel();
        lolNameMay = new javax.swing.JLabel();
        lolNameMin = new javax.swing.JLabel();
        txtNumberCharacters = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lolLetter = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNumberCharacters = new javax.swing.JLabel();
        lolCharacters = new javax.swing.JLabel();
        txtLetter = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("String Manager");
        setPreferredSize(new java.awt.Dimension(445, 500));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Your name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 204, 51));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnShow.setBackground(new java.awt.Color(255, 204, 102));
        btnShow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnShow.setText("SHOW");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnSpanish.setBackground(new java.awt.Color(51, 102, 255));
        btnSpanish.setText("SP");
        btnSpanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpanishActionPerformed(evt);
            }
        });

        btnEnglish.setBackground(new java.awt.Color(255, 255, 0));
        btnEnglish.setText("EN");
        btnEnglish.setEnabled(false);
        btnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblName)
                        .addGap(153, 153, 153)
                        .addComponent(btnEnglish)
                        .addGap(18, 18, 18)
                        .addComponent(btnSpanish)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEnglish)
                        .addComponent(btnSpanish)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelName.setText("Your name is:");

        lolName.setText("_");

        jLabelNameMay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNameMay.setText("Your name in MAY:");

        jLabelNameMin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNameMin.setText("Your name in MIN:");

        lolNameMay.setText("_");

        lolNameMin.setText("_");

        btnSearch.setBackground(new java.awt.Color(153, 153, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearch.setText(" Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lolLetter.setText("_");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabelNumberCharacters.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNumberCharacters.setText(" Number of characters of the name:");

        lolCharacters.setText("_");

        txtLetter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLetter.setText("LETTER:");

        javax.swing.GroupLayout jPInformationLayout = new javax.swing.GroupLayout(jPInformation);
        jPInformation.setLayout(jPInformationLayout);
        jPInformationLayout.setHorizontalGroup(
            jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformationLayout.createSequentialGroup()
                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInformationLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelNameMay)
                        .addGap(18, 18, 18)
                        .addComponent(lolNameMay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPInformationLayout.createSequentialGroup()
                        .addComponent(jLabelNameMin)
                        .addGap(22, 22, 22)
                        .addComponent(lolNameMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPInformationLayout.createSequentialGroup()
                        .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInformationLayout.createSequentialGroup()
                                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabelNumberCharacters))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lolCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPInformationLayout.createSequentialGroup()
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lolName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPInformationLayout.createSequentialGroup()
                .addComponent(txtNumberCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(txtLetter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lolLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPInformationLayout.setVerticalGroup(
            jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(lolName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lolNameMay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNameMay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameMin)
                    .addComponent(lolNameMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumberCharacters)
                    .addComponent(lolCharacters))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(jPInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(lolLetter)
                    .addComponent(txtLetter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtName.setText(null);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        yName=txtName.getText();
        
        System.out.println("Your name is: "+yName);
        
        String [] palabras = yName.split(" ");
        String NewName=May_Min(palabras);
        lolName.setText(NewName);
        
        lolNameMay.setText(yName.toUpperCase());
        lolNameMin.setText(yName.toLowerCase());
        lolCharacters.setText(""+yName.length());

        
    }//GEN-LAST:event_btnShowActionPerformed

    public String May_Min(String cadenareal[]){ 
            String nuevacadena=""; 
            for(int i = 0; i < cadenareal.length; i++) {
            nuevacadena += cadenareal[i].substring(0, 1).toUpperCase() + cadenareal[i].substring(1, cadenareal[i].length()).toLowerCase() + " ";
            }
            nuevacadena = nuevacadena.trim();
        return nuevacadena;
    }

    
    
    
    private void btnSpanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpanishActionPerformed
        btnEnglish.setEnabled(true);
        lblName.setText("Su nombre:");
        btnShow.setText("MOSTRAR");
        btnReset.setText("BORRAR");
        jPInformation.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));
        TitledBorder titledBorder = (TitledBorder)jPInformation.getBorder();
        titledBorder.setTitleColor(Color.RED);
        jLabelName.setText("Su nombre es:");
        jLabelNameMay.setText("Su nombre en Mayuscula:");
        jLabelNameMin.setText("Su nombre en Minuscula:");
        jLabelNumberCharacters.setText("Numero de Caracteres de el Nombre:");
        txtLetter.setText("Letra:");
        btnSearch.setText("Buscar");
        btnSpanish.setEnabled(false);
    }//GEN-LAST:event_btnSpanishActionPerformed

    private void btnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnglishActionPerformed
        btnSpanish.setEnabled(true);
        lblName.setText("Your Name:");
        btnShow.setText("SHOW");
        btnReset.setText("RESET");
        jPInformation.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));
        TitledBorder titledBorder = (TitledBorder)jPInformation.getBorder();
        titledBorder.setTitleColor(Color.RED);
        jLabelName.setText("Your name is:");
        jLabelNameMay.setText("Your name in MAY:");
        jLabelNameMin.setText("Your name in MIN:");
        jLabelNumberCharacters.setText("Number of characters of the name:");
        btnSearch.setText("Search");
        txtLetter.setText("LETTER:");
        btnEnglish.setEnabled(false);

    }//GEN-LAST:event_btnEnglishActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        int NCharacters=Integer.parseInt(txtNumberCharacters.getText());    
        lolLetter.setText(""+yName.charAt(NCharacters-1));
    }//GEN-LAST:event_btnSearchActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StringManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnglish;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSpanish;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameMay;
    private javax.swing.JLabel jLabelNameMin;
    private javax.swing.JLabel jLabelNumberCharacters;
    private javax.swing.JPanel jPInformation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lolCharacters;
    private javax.swing.JLabel lolLetter;
    private javax.swing.JLabel lolName;
    private javax.swing.JLabel lolNameMay;
    private javax.swing.JLabel lolNameMin;
    private javax.swing.JLabel txtLetter;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumberCharacters;
    // End of variables declaration//GEN-END:variables
}
