/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author usuario
 */
public class Colors_V2 extends javax.swing.JFrame {

    /**
     * Creates new form Mens
     */
    public Colors_V2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        Btn_letra = new javax.swing.JButton();
        Btn_Mensaje = new javax.swing.JButton();
        Btn_fondo = new javax.swing.JButton();
        Btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        txtMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMensajeKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtMensaje);

        Btn_letra.setText("Color Letra");
        Btn_letra.setToolTipText("Haz click para cambiar el color de la letra");
        Btn_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_letraActionPerformed(evt);
            }
        });

        Btn_Mensaje.setText("Mensaje");
        Btn_Mensaje.setToolTipText("Haz click para mostrar el mensaje");
        Btn_Mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MensajeActionPerformed(evt);
            }
        });

        Btn_fondo.setText("Color Fondo");
        Btn_fondo.setToolTipText("Haz click para cambiar el color del fondo");
        Btn_fondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_fondoActionPerformed(evt);
            }
        });

        Btn_salir.setText("Salir");
        Btn_salir.setToolTipText("Haz click para salir de la palicación");
        Btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Btn_letra)
                        .addGap(34, 34, 34)
                        .addComponent(Btn_fondo)
                        .addGap(28, 28, 28)
                        .addComponent(Btn_salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(Btn_Mensaje)
                    .addContainerGap(400, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_letra)
                    .addComponent(Btn_fondo)
                    .addComponent(Btn_salir))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(310, Short.MAX_VALUE)
                    .addComponent(Btn_Mensaje)
                    .addGap(38, 38, 38)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_MensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MensajeActionPerformed
        String mensaje="La gloria de Dios\n" +
"Maneja mi vida\n" +
"Con hilos de amor\n" +
"Que puso en mi alma\n" +
"Me lleva hasta el\n" +
"La gloria de Dios\n" +
"Gigante y sagrada\n" +
"Me carga en sus brazos\n" +
"Alienta mis pasos\n" +
"Me llena de paz y miel\n" +
"Sale a jugar\n" +
"Cuando me viene a ver\n" +
"Y me deja ganar\n" +
"De la Gloria de Dios tendré\n" +
"El descanso para mis pies\n" +
"Con su manto mi frio\n" +
"Desaparecerá y descansaré\n" +
"De la Gloria de Dios vendrá\n" +
"Bendición y abundante pan\n" +
"Para ti y para mí\n" +
"Y a quien quiera venir\n" +
"A la Gloria de Dios\n" +
"La gloria de Dios\n" +
"Maneja mi vida\n" +
"Con hilos de amor\n" +
"Que puso en mi alma\n" +
"Me lleva hasta el\n" +
"La gloria de Dios\n" +
"Gigante y sagrada\n" +
"Me carga en sus brazos\n" +
"Alienta mis pasos\n" +
"Me llena de paz y miel\n" +
"Sale a jugar\n" +
"Cuando me viene a ver\n" +
"Y me deja ganar\n" +
"En la Gloria de Dios tendré\n" +
"El descanso para mis pies\n" +
"Con su manto mi frio\n" +
"Desaparecerá y…";
        
txtMensaje.setText(mensaje);
        
    }//GEN-LAST:event_Btn_MensajeActionPerformed

    private void Btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_salirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_Btn_salirActionPerformed

    private void Btn_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_letraActionPerformed
       Color c=JColorChooser.showDialog(rootPane,"Por favor selecciona un color para establecerlo a el color de letra", this.getForeground());
       txtMensaje.setForeground(c);
    }//GEN-LAST:event_Btn_letraActionPerformed

    private void Btn_fondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_fondoActionPerformed
       Color c=JColorChooser.showDialog(rootPane,"Por favor selecciona un color para establecerlo a el fondo", this.getBackground());
       txtMensaje.setBackground(c);
    }//GEN-LAST:event_Btn_fondoActionPerformed

    private void txtMensajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensajeKeyTyped
        char H=evt.getKeyChar();                                    //declaro variable tipo string
        if ((H<'0' || H>'9') && (H<'.' || H>'.'))
        {
            getToolkit().beep();
            evt.consume();
        }
        if ((H<'a' || H>'z') && (H<'.' || H>'.'))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtMensajeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colors_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colors_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colors_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colors_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colors_V2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Mensaje;
    private javax.swing.JButton Btn_fondo;
    private javax.swing.JButton Btn_letra;
    private javax.swing.JButton Btn_salir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables
}
