package ejercicios;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JUAN CARLOS ASTAIZA ORDOÑEZ
 */
public class Colors extends javax.swing.JFrame {

    /**
     * Creates new form Colors
     */
    int cont=0,Nactual_vector=1;
        String[] colorSeleccionado = new String[2];

    public Colors() {
        initComponents();
        //Añadir datos a JCombobox
        //Yellow, Red, Blue, Green, Black, White, Brown
        //*****************************************************************
        //----Primera forma ARREGLO--      
        /*String[] colores={"Yellow","Red","Blue","Green","Black","White","Brown"};
        for (String color : colores) {
            cmbColors.addItem(color);  
        }*/
        //********************************************************************
        //----Segunda forma-- (FORMA DIRECTA)     
        //********************************************************************  
        /*cmbColors.addItem("Yellow");
        cmbColors.addItem("Red");
        cmbColors.addItem("Blue");
        cmbColors.addItem("Green");
        cmbColors.addItem("Black");
        cmbColors.addItem("White");
        cmbColors.addItem("Brown");*/
        //********************************************************************
        //----Tercera forma-- VECTOR  
        /*colores=new String[100];
        colores[0]="Yellow";
        colores[1]="Blue";
        colores[2]="Green";
        colores[3]="Black";
        colores[4]="White";
        colores[5]="Yellow";
        colores[6]="Brown";
        
        for (String color: colores) {
            cmbColors.addItem(color);  
        }*/

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbColors = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblColorSelected = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblChangeColor_Current = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblChangeColor_Previous = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtComboxColors = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colors");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Colors");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 710, 40);

        cmbColors.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yellow", "Red", "Blue", "Green", "Black", "White", "Brown" }));
        jPanel1.add(cmbColors);
        cmbColors.setBounds(40, 90, 310, 30);

        jLabel2.setText("Choose a color:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("The color selected is:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 190, 140, 30);

        lblColorSelected.setText("...");
        jPanel1.add(lblColorSelected);
        lblColorSelected.setBounds(170, 190, 180, 30);

        jButton1.setText("What color did you select?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 140, 310, 40);

        lblChangeColor_Current.setBackground(new java.awt.Color(255, 255, 255));
        lblChangeColor_Current.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangeColor_Current.setText("...");
        lblChangeColor_Current.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChangeColor_Current.setOpaque(true);
        jPanel1.add(lblChangeColor_Current);
        lblChangeColor_Current.setBounds(40, 250, 140, 70);

        jLabel5.setText("Current color:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 140, 14);

        jLabel6.setText("Previous color:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 230, 140, 14);

        lblChangeColor_Previous.setBackground(new java.awt.Color(255, 255, 255));
        lblChangeColor_Previous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangeColor_Previous.setText("...");
        lblChangeColor_Previous.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblChangeColor_Previous.setOpaque(true);
        jPanel1.add(lblChangeColor_Previous);
        lblChangeColor_Previous.setBounds(210, 250, 140, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new colors"));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel4.setText("Color name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 30, 230, 20);

        txtComboxColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComboxColorsActionPerformed(evt);
            }
        });
        jPanel2.add(txtComboxColors);
        txtComboxColors.setBounds(20, 60, 220, 30);

        jButton2.setText("Add color to combobox");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 100, 220, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(380, 60, 270, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cont++;

        String Colorantes=colorSeleccionado[0];
        String colorActual = cmbColors.getSelectedItem().toString();
        //getSelectedIndex() Permite mostrar la posicion 
       /*int selecionado = cmbColors.getSelectedIndex();
        System.out.println(selecionado);*/
        lblColorSelected.setText(colorActual); 
        
        if(cont==1){
            colorSeleccionado[0] = colorActual;
            colorSeleccionado[1] = "";
        }else{
            colorSeleccionado[0] = colorActual; 
            colorSeleccionado[1] = Colorantes; 
        }

     
            switch(colorSeleccionado[0]){
                case "Yellow": 
                    lblChangeColor_Current.setBackground(Color.yellow);
                    break;
                case "Red": 
                    lblChangeColor_Current.setBackground(Color.red);  
                    break;
                case "Blue": 
                    lblChangeColor_Current.setBackground(Color.blue);   
                    break;
                case "Green": 
                    lblChangeColor_Current.setBackground(Color.green);   
                    break;
                case "Black": 
                    lblChangeColor_Current.setBackground(Color.black);   
                    break;
                case "White": 
                    lblChangeColor_Current.setBackground(Color.white);   
                    break;
                case "Brown": 
                    Color colorCafe=new Color(121, 58, 44);
                    lblChangeColor_Current.setBackground(colorCafe);   
                    break;
            }
            
            switch(colorSeleccionado[1]){
                case "Yellow": 
                    lblChangeColor_Previous.setBackground(Color.yellow);
                    break;
                case "Red": 
                    lblChangeColor_Previous.setBackground(Color.red);  
                    break;
                case "Blue": 
                    lblChangeColor_Previous.setBackground(Color.blue);   
                    break;
                case "Green": 
                    lblChangeColor_Previous.setBackground(Color.green);   
                    break;
                case "Black": 
                    lblChangeColor_Previous.setBackground(Color.black);   
                    break;
                case "White": 
                    lblChangeColor_Previous.setBackground(Color.white);   
                    break;
                case "Brown": 
                    Color colorCafe=new Color(121, 58, 44);
                    lblChangeColor_Previous.setBackground(colorCafe);   
                    break;
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtComboxColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComboxColorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComboxColorsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String color_add=txtComboxColors.getText();
        cmbColors.addItem(color_add);
        txtComboxColors.setText("");
        cmbColors.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbColors;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChangeColor_Current;
    private javax.swing.JLabel lblChangeColor_Previous;
    private javax.swing.JLabel lblColorSelected;
    private javax.swing.JTextField txtComboxColors;
    // End of variables declaration//GEN-END:variables
}
