/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Corte_2;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author juanc
 */
public class Number_race extends javax.swing.JFrame {

    /**
     * Creates new form Number_race
     */
    int cont=1;
    int Num_jugadores,nivelSeleccionado;
    String numeroJugadores;
    
    ArrayList<String> jugadores = new ArrayList<String>();
    

    public Number_race() {
        initComponents();
        //No permitimos cambiar tamaño
        setResizable(false);
        //Centramos el JFrame en nuestra Pantalla
        setLocationRelativeTo(null);
        //Cambiar el icono a un frame
        setIconImage(new ImageIcon(getClass().getResource("car.png")).getImage());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpanel_configZone = new javax.swing.JPanel();
        cmb_numberPlayers = new javax.swing.JComboBox<>();
        cmb_Level = new javax.swing.JComboBox<>();
        btn_startGame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jpanelPairs = new javax.swing.JPanel();
        lblPairs = new javax.swing.JLabel();
        jpanel_scoresZone = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_turnPlayer = new javax.swing.JLabel();
        lbl_advancedPositions = new javax.swing.JLabel();
        lbl_missingPositions = new javax.swing.JLabel();
        lbl_returns = new javax.swing.JLabel();
        jpanelWinner = new javax.swing.JPanel();
        lblWinner = new javax.swing.JLabel();
        jpanel_playZone2 = new javax.swing.JPanel();
        btn_playPlayerNo = new javax.swing.JButton();
        lblD1 = new javax.swing.JLabel();
        lblD2 = new javax.swing.JLabel();
        btn_configParams = new javax.swing.JButton();
        btn_aboutOf = new javax.swing.JButton();
        btn_tryAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number race");

        jpanelPrincipal.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Corte_2/banner.png"))); // NOI18N

        jpanel_configZone.setBackground(new java.awt.Color(102, 255, 102));
        jpanel_configZone.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Config zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 14))); // NOI18N

        cmb_numberPlayers.setEnabled(false);

        cmb_Level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic [50]", "Intermediate[100]", "Advanced[200]" }));
        cmb_Level.setEnabled(false);

        btn_startGame.setBackground(new java.awt.Color(204, 0, 0));
        btn_startGame.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btn_startGame.setForeground(new java.awt.Color(255, 255, 255));
        btn_startGame.setText("Start game");
        btn_startGame.setEnabled(false);
        btn_startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startGameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Level:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Number of players:");

        javax.swing.GroupLayout jpanel_configZoneLayout = new javax.swing.GroupLayout(jpanel_configZone);
        jpanel_configZone.setLayout(jpanel_configZoneLayout);
        jpanel_configZoneLayout.setHorizontalGroup(
            jpanel_configZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_configZoneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpanel_configZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(btn_startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Level, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_numberPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpanel_configZoneLayout.setVerticalGroup(
            jpanel_configZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_configZoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_numberPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(cmb_Level, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpanelPairs.setBackground(new java.awt.Color(102, 255, 102));
        jpanelPairs.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Pairs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 14))); // NOI18N

        lblPairs.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        lblPairs.setForeground(new java.awt.Color(255, 51, 51));
        lblPairs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPairs.setText("0");

        javax.swing.GroupLayout jpanelPairsLayout = new javax.swing.GroupLayout(jpanelPairs);
        jpanelPairs.setLayout(jpanelPairsLayout);
        jpanelPairsLayout.setHorizontalGroup(
            jpanelPairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
            .addGroup(jpanelPairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelPairsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPairs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpanelPairsLayout.setVerticalGroup(
            jpanelPairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
            .addGroup(jpanelPairsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelPairsLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblPairs, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpanel_scoresZone.setBackground(new java.awt.Color(102, 255, 102));
        jpanel_scoresZone.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Scores zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Turn player:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Advanced positions:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Missing positions:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Returns:");

        lbl_turnPlayer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_turnPlayer.setForeground(new java.awt.Color(0, 102, 0));
        lbl_turnPlayer.setText("#");

        lbl_advancedPositions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_advancedPositions.setForeground(new java.awt.Color(0, 102, 0));
        lbl_advancedPositions.setText("#");

        lbl_missingPositions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_missingPositions.setForeground(new java.awt.Color(0, 102, 0));
        lbl_missingPositions.setText("#");

        lbl_returns.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_returns.setForeground(new java.awt.Color(0, 102, 0));
        lbl_returns.setText("#");

        javax.swing.GroupLayout jpanel_scoresZoneLayout = new javax.swing.GroupLayout(jpanel_scoresZone);
        jpanel_scoresZone.setLayout(jpanel_scoresZoneLayout);
        jpanel_scoresZoneLayout.setHorizontalGroup(
            jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_scoresZoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_scoresZoneLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_returns))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_scoresZoneLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_missingPositions))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_scoresZoneLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(lbl_advancedPositions))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_scoresZoneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_turnPlayer)))
                .addGap(38, 38, 38))
        );
        jpanel_scoresZoneLayout.setVerticalGroup(
            jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_scoresZoneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_turnPlayer))
                .addGap(11, 11, 11)
                .addGroup(jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_advancedPositions))
                .addGap(11, 11, 11)
                .addGroup(jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_missingPositions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_scoresZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_returns))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelWinner.setBackground(new java.awt.Color(102, 255, 102));
        jpanelWinner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Winner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 14))); // NOI18N

        lblWinner.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        lblWinner.setForeground(new java.awt.Color(0, 153, 153));
        lblWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWinner.setText("?");

        javax.swing.GroupLayout jpanelWinnerLayout = new javax.swing.GroupLayout(jpanelWinner);
        jpanelWinner.setLayout(jpanelWinnerLayout);
        jpanelWinnerLayout.setHorizontalGroup(
            jpanelWinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
            .addGroup(jpanelWinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelWinnerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jpanelWinnerLayout.setVerticalGroup(
            jpanelWinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
            .addGroup(jpanelWinnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelWinnerLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpanel_playZone2.setBackground(new java.awt.Color(102, 255, 102));
        jpanel_playZone2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Play zone", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semibold", 1, 14))); // NOI18N

        btn_playPlayerNo.setBackground(new java.awt.Color(0, 102, 0));
        btn_playPlayerNo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btn_playPlayerNo.setForeground(new java.awt.Color(255, 255, 255));
        btn_playPlayerNo.setText("Play - Player #");
        btn_playPlayerNo.setEnabled(false);
        btn_playPlayerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playPlayerNoActionPerformed(evt);
            }
        });

        lblD1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCorte2/question.png"))); // NOI18N

        lblD2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblD2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCorte2/question.png"))); // NOI18N

        javax.swing.GroupLayout jpanel_playZone2Layout = new javax.swing.GroupLayout(jpanel_playZone2);
        jpanel_playZone2.setLayout(jpanel_playZone2Layout);
        jpanel_playZone2Layout.setHorizontalGroup(
            jpanel_playZone2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_playZone2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpanel_playZone2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_playZone2Layout.createSequentialGroup()
                        .addComponent(lblD1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblD2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_playPlayerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jpanel_playZone2Layout.setVerticalGroup(
            jpanel_playZone2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_playZone2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_playZone2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblD2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_playPlayerNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        btn_configParams.setBackground(new java.awt.Color(255, 102, 0));
        btn_configParams.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btn_configParams.setForeground(new java.awt.Color(255, 255, 255));
        btn_configParams.setText("Config params");
        btn_configParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configParamsActionPerformed(evt);
            }
        });

        btn_aboutOf.setBackground(new java.awt.Color(0, 0, 102));
        btn_aboutOf.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btn_aboutOf.setForeground(new java.awt.Color(255, 255, 255));
        btn_aboutOf.setText("About of ");
        btn_aboutOf.setEnabled(false);
        btn_aboutOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutOfActionPerformed(evt);
            }
        });

        btn_tryAgain.setBackground(new java.awt.Color(204, 0, 0));
        btn_tryAgain.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        btn_tryAgain.setForeground(new java.awt.Color(255, 255, 255));
        btn_tryAgain.setText("Try again");
        btn_tryAgain.setEnabled(false);
        btn_tryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tryAgainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelPrincipalLayout = new javax.swing.GroupLayout(jpanelPrincipal);
        jpanelPrincipal.setLayout(jpanelPrincipalLayout);
        jpanelPrincipalLayout.setHorizontalGroup(
            jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpanel_configZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_playZone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelPairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_scoresZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_configParams, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aboutOf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tryAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jpanelPrincipalLayout.setVerticalGroup(
            jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpanel_scoresZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanel_configZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(jpanelPrincipalLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btn_configParams, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tryAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_aboutOf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jpanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_playZone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelPairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startGameActionPerformed
        //VALIDAMOS LA CANTIDAD DE JUGADORES HA SIDO SELECCIONADO CORRECTAMENTE
        numeroJugadores= cmb_numberPlayers.getSelectedItem().toString();
        if(numeroJugadores.equals("Seleccione una opción")){
           JOptionPane.showMessageDialog(null, "Seleccione la cantidad de jugadores.");
        }else if(numeroJugadores.equals("1")){
           JOptionPane.showMessageDialog(null, "Cantidad de jugadores no permitida. Debe ser mayor que 1.");        
        }else{
            //Botones y jComboBox a editables
            btn_tryAgain.setEnabled(true);
            btn_aboutOf.setEnabled(true);
            btn_playPlayerNo.setEnabled(true);

            //Botones y jComboBox no editables. 
            cmb_Level.setEnabled(false);
            cmb_numberPlayers.setEnabled(false);
            btn_startGame.setEnabled(false);
            
        

            btn_playPlayerNo.setText("Play - Player 1");
  
        }
            
        int nivel = cmb_Level.getSelectedIndex();
              if(nivel==0){ //basic
            nivelSeleccionado=50;
        }else if(nivel==1){ //intermediate
            nivelSeleccionado=100;
        }else{ //advanced
            nivelSeleccionado=200;
        }
        System.out.println("jugadores: "+numeroJugadores);
        System.out.println("nivel: "+nivelSeleccionado);
       
    }//GEN-LAST:event_btn_startGameActionPerformed

    private void btn_configParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configParamsActionPerformed
        String[] options = {"Si", "No"};
        boolean no=false;
        do{   
            int boton = JOptionPane.showOptionDialog(null, "Desea agregar el número de jugadores que desean jugar?", "Config Params", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

            switch(boton){
                case 0: //SI
                    int respSi = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea agregar el número de jugadores que desean jugar?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

                    if(respSi==0){
                        boolean n_bandera=false;
                        do{
                            try{
                                //(n_bandera2) Validar numero de JUGADORES ingresado por el usuario sea mayor o igual a 2
                                boolean n_bandera2=false;
                                do{
                                    Num_jugadores=Integer.parseInt(javax.swing.JOptionPane.showInputDialog("Introduce la cantidad de jugadores: "));
                                    n_bandera=true;
                                    no=true;  
                                    if(Num_jugadores<2){
                                        n_bandera2=false;
                                    }else{
                                        n_bandera2=true;
                                        //PERMITE AÑADIR DATOS AL ARRAYLIST
                                        jugadores.add("Seleccione una opción");//0
                                        for (int i = 1; i <=Num_jugadores ; i++) {
                                            jugadores.add(Integer.toString(i));
                                        }
                                        //PERMITE AÑADIR DATOS AL JCOMBOBOX
                                        for (String jugador : jugadores) {
                                            cmb_numberPlayers.addItem(jugador);  
                                        }
                                        btn_startGame.setEnabled(true);
                                        cmb_numberPlayers.setEnabled(true);
                                        cmb_Level.setEnabled(true);
                                        btn_configParams.setEnabled(false);
                                    }
                                }while(!n_bandera2);
                            } catch(NumberFormatException e){
                                JOptionPane.showMessageDialog(null, "Solo se permiten números.");
                                n_bandera=false;
                                no=false;
                            }                        
                        }while(!n_bandera);                    
                    }else{
                        no=true;
                        btn_startGame.setEnabled(true);
                        cmb_numberPlayers.setEnabled(true);
                        cmb_Level.setEnabled(true);
                        btn_configParams.setEnabled(false);
                        jugadores.add("Seleccione una opción");//0
                        jugadores.add("1");//1
                        jugadores.add("2");//2
                        jugadores.add("3");//3
                        for (String jugador : jugadores) {
                            cmb_numberPlayers.addItem(jugador);  
                        }
                    }
                    break;
                case 1: //NO
                    
                    int respNo = JOptionPane.showConfirmDialog(null, "¿Esta seguro que NO desea agregar el número de jugadores que desean jugar?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                
                    if(respNo==0){
                        no=true;
                        btn_startGame.setEnabled(true);
                        cmb_numberPlayers.setEnabled(true);
                        cmb_Level.setEnabled(true);
                        btn_configParams.setEnabled(false);
                        jugadores.add("Seleccione una opción");//0
                        jugadores.add("1");//1
                        jugadores.add("2");//2
                        jugadores.add("3");//3
                        for (String jugador : jugadores) {
                            cmb_numberPlayers.addItem(jugador);  
                        }
                    }else{
                        no=false;
                    }
                    break;

            }
        }while(!no);       
    
    }//GEN-LAST:event_btn_configParamsActionPerformed

    private void btn_aboutOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutOfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutOfActionPerformed

    private void btn_tryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tryAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tryAgainActionPerformed

    private void btn_playPlayerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playPlayerNoActionPerformed
        cont++;
        btn_playPlayerNo.setText("Play - Player "+cont);
        if (cont==Integer.parseInt(numeroJugadores)) {
            cont=0;
        }

    }//GEN-LAST:event_btn_playPlayerNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Number_race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Number_race().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aboutOf;
    private javax.swing.JButton btn_configParams;
    private javax.swing.JButton btn_playPlayerNo;
    private javax.swing.JButton btn_startGame;
    private javax.swing.JButton btn_tryAgain;
    private javax.swing.JComboBox<String> cmb_Level;
    private javax.swing.JComboBox<String> cmb_numberPlayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jpanelPairs;
    private javax.swing.JPanel jpanelPrincipal;
    private javax.swing.JPanel jpanelWinner;
    private javax.swing.JPanel jpanel_configZone;
    private javax.swing.JPanel jpanel_playZone2;
    private javax.swing.JPanel jpanel_scoresZone;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblPairs;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JLabel lbl_advancedPositions;
    private javax.swing.JLabel lbl_missingPositions;
    private javax.swing.JLabel lbl_returns;
    private javax.swing.JLabel lbl_turnPlayer;
    // End of variables declaration//GEN-END:variables
}
